### ISSUE TITLE
Oganizational Chart

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#112]
## Rationale

Many organizations ask to be able to have an organization diagram in the platform. In order to implement the relation between user we should be able to identified the manager of the users.

##### Profile

- P1 - New system attribute "Manager"
   - multi-valued attribute
   - new attribute type: user
- P1 - Display:
   - Avatar
   - Full name (first name + last name)
- P1 - Hover:
   - Pop-up card of the user
- P1 - Click: open the new organization chart feature
- Edition:
   - P1 - AD or LDAP knowing that the information provided by LDAP is the LDAP reference type CN
   - P1 - CSV import thanks to user name attribute
   - P1 - for the user:  thanks to a user selector from the contact information edition
- P1 - In case of the user identified in the attribute is inactive:
   - for member/platform/user: the field is hidden
   - for member/platform/administrator and member/platform/user in its profile: the field is displayed as if the field is hidden
- P1 - In case the attribute is inactive:
   - the field is not displayed at all
   - if the field is inactive could we still provide value thanks to CSV or AS/LDAP for it?
   - QUID about the organizational chart?

##### Administration
- P1 - default values:
   - name: Manager 
   - Visible: True
   - Editable: False
   - Non-maskable: False
   - Required: False
   - Multi-valued: True
   - Group synchronize: False
   - Active: True
   - No parent
- the attribute can be edited by the administrator
   - P1 - rename, visible, non-maskable, required, group synchronized, active
   - P1 - multi-valued can't be changed
   - P1- editable can be changed

![image](https://github.com/Meeds-io/MIPs/assets/105866381/59e5a382-5243-4296-83b0-d65e99f2d67d)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/d03ddfc3-bc7c-45de-bb50-2dc8cbbe9cab)

#### Organization chart

- New portlet Organization chart
 - Portlet properties: 
   - in the section Tools
   - permission to add it: member/platform/administration
    - Settings:
    - Portlet settings: 
      - Display name: Organization chart
      - Hide info bar
      - Hide portlet mode
      - Hide Window state
    - Access permission: member/platform/user
    - No other settings tabs

- Display hierarchical relationships
  - in the middle the current user we are looking
  - above the manager (N+1)
  - below the people who have the current user as manager (N-1)
  - the users are displayed with cards

  - Current user card:
    - Full name
    - Avatar
    - 3 fields (1 principal and 2 secondaries) that can be defined by the administrator by interface in a drawer
      - if no data or the attribute is hidden by the user then the field is not displayed
    - See more that linked to the profile page
    - No click action on the card
    - this card layout should replace the current card in the user list of the people page
    - CTA buttons using only icons
      - Mail: to send a mail with the default mailing software of the device
        - if no data in the attribute email or hidden by the user the CTA is displayed as disabled and not clickable
      - Kudos

  - N+1 card:
    - Full name
    - Avatar
    - 1 field (same as the principal of the current user card)
    - Click on the card make the user as current user

  - N-1 card:
    -  Full name
    - Avatar
    - 1 field (same as the principal of the current user card)
    - chip to indicate the number of N-1 user linked to this users - no action on this chip
    - Click on the card make the user as current user

  - Fields setting
    - a new drawer to select 
       - the 3 fields of the cards
       - the attribute "manager" of the profile from which the organizational chart is based
       - the user in the center of the organizational chart
    - attribute "manager" choice
       - dropdown selector to choose from the profile attribute which attribute "user" is used to generate the organization chart. We select the manager attribute we want
       - by default, it's the default manager field that is selected
    - User at the center of the organizational chart
          - user selector to choose only one user that will be the user in the center of the organizational chart
          - by default, it's the user from which we have open the organizational chart
          - if it's a customer organizational chart created on a new page, we have to select the user.
          - It's a mandatory field
    - Field of the cards
       - 3 dropdowns to select profile attribute
       - the field settings are different from one portlet to another so we could manage separately the different organization charts
       - default values:
         - principal field: function
         - second field: Team
         - Third field: city

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/ebb14cc0-4621-42e9-92b9-20f2a11bdb2e)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/415ddbcf-3b06-43f4-b2ec-8e5011120108)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/22d85990-28ec-460d-9045-572e5a925cc0)

Expand view

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/99c30751-1da9-41e9-b2dc-b70d8211f267)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/4f92b2df-9ad9-4e3a-bbea-2bc40022dd8a)

  - Download
    - download the current view of the organizational chart
    - if possible a PDF with all the text that can be search in the PDF
    - if not possible an image of the current view

- New page with this portlet
  - a new page with the new portlet inside 

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/44c44739-dafa-4035-ac32-88b5bab1c8ab)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/fd3524d9-4b18-47c4-aea3-167a2280ada8)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/7573f9be-01d6-42e9-86be-bb6f74eee6cb)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/d9d9c0d0-d6e2-4da2-b285-f404445efe64)

### Expected Volume & Performance
N/A

### Security
This feature will use existing security mechanisms

### Extensibility
No extensibility requirements

### Configurability
 Configurations will be added for :
  - The new field Manager in the list of Profile property settings
  - The new page containing the **Organizational chart**

### Upgradability
 - This feature will add new data (manager field) and will use existing user data without changing it

### Requirements related to existing features 
 - A new profile property setting **Manager** will be added by configuration to the list of properties and will be available by default to be used by administrators
 - The new field **Manager** will be displayed in the user profile
 - A new portlet Org chart will be based on the values of the manager field and use it to build the organigram of the company 
 - A drawer will be added to configure the fields displayed in the user cards

### Feature Flags
No feature flag will be added, unless the org chat feature is not needed on Meeds side
should we disable by default the Org chart for Meeds ?

### Other Non Functional Requirements
Make sure that the new developments respect the accessibility requirements

###  Impacts
Documentation
Training

### Security
 - We will follow the existing recommendation and best practices of the security 
 - Rest endpoints should be configured correctly with the @RolesAllowed annotation
 - Only administrators will be able to alter the field manager, this restriction should be integrated in the front end application and in the Rest API

### Access
 - All users will be able to view the added data
 - Administrators will be able to configure the portlet Org chart and set the fields to display inside the people card
 
### Rest API design 
 - Organizational chart :
  - The manager information will be added to the response returned by the existing Rest endpoint that returns the social user profile, it should be enabled/disabled in the response using the expand query parameter
  - The number of collaborators will be added to the response returned by the existing Rest endpoint that returns the social user profile
 - Drawer to Configure Organizational chart portlet
  - A new Rest endpoint to configure the list of fields to show on the user card inside the Organizational Chart portlet 
  - Those settings will be saved as portlet preferences of the portlet.

### Portlet Vue & Vuetify
 - The **Organizational Chart** is a new Vuejs portlet
 - The portlet will use existing VueJs components
 - Export to PDF : jspdf & html2canvas libraries will be used to generate the PDF file
  - This will require moving the libraries from Notes module to the Social module

### Services & processing
 - Functions will be added to :
  - Retrieve the number of collaborators for a requested user

### Data and persistence
No new data model to add
 - Organizational chart settings will be saved as portlet preferences
 - Manager field will be saved in the user profile properties, We will use the userName of the manager as the value of this field.
 
### Migration strategy
 - Profile index should be updated to make all fields use the keyword type
 - Full reindexation of user profiles may be needed to update the mapping and refresh unindexed data

### Annexes
Reasoning that explain the technical choices
Impacts
References

**Comment by Julien-Dubois-eXo** [comment]
@ahamdi @rdenarie can you complete the technical part please?

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds could you check the functional part please?

**Comment by srenault-meeds** [comment]
Hello, what is the rationale please?
I mean, which problem are you trying to solve?
Thanks

**Comment by Julien-Dubois-eXo** [comment]
Edited

**Comment by srenault-meeds** [comment]
Thanks. It looks like this MIP is highly related to an organizational chart which Meeds doesn't provide.
If such feature is planned to be worked, then I suggest to work this manager field in the same MIP as it is related.
Thanks

**Comment by rdenarie** [comment]
The only subject of this MIP is to allow to have a field with a type "user" in the profile, in addition of the type text.
This is a prerequisite to organizational chart feature, which will not be in meeds, and not in a MIP.

The "user" type is in Meeds code, so this MIP.
The org chart will use this new type, and will not be in Meeds code.

If you prefer, we can make a simple issue to add the new type

**Comment by srenault-meeds** [comment]
I didn't know that this chart won't be in Meeds. let's discuss about it ;-)

**Comment by rdenarie** [comment]
It was my understanding. Perhaps wrong. cc @margondicco

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds the manager field will start soon. Probably the beginning of next week. Could you check the functional part please? 

@margondicco  For the export do you have an idea of what information (especially the relation between people) you want? I have difficulty seeing how to organize it in a CSV. @srenault-meeds your opinion would be valuable too. 

The technical part of the manager field will be provided in the day coming.

**Comment by plamarque** [comment]
Renamed this MIP to something simpler. The manager field being just a requirement for the org chart

**Comment by ahamdi** [comment]
@boubaker @rdenarie Ready for tech review

**Comment by rdenarie** [comment]
We wait go fonc before requesting the go tech

 @Julien-Dubois-eXo and @srenault-meeds can you synchronize to give the go func ?

Thanks

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have added some mock-ups for:

1. adding a manager in the contact information drawer manually
2. Organizational chart based on what we have discussed last time

Could you check to give go func for the end of this week? We will start at the beginning of next the manager.

**Comment by boubaker** [comment]
> [@boubaker](https://github.com/boubaker) [@rdenarie](https://github.com/rdenarie) Ready for tech review

Yes. Thanks for the technical details. Let's wait for the Go func first to ensure that the functional requirement doesn't change (thus the technical requirements doesn't change neither) and then I 'll take care of it.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have added the design for the organizational chart setting drawer.

**Comment by srenault-meeds** [comment]
Hello,

Feedbacks:

> if the field is inactive could we still provide value thanks to CSV or AS/LDAP for it?
QUID about the organizational chart?

Question in a MIP. Did you get your answers? Are there still questions?

> Mail: to send a mail with the default mailing software of the device

What is this?

> chip to indicate the number of N-1 user linked to this users - no action on this chip

Tooltip?

> if possible a PDF with all the text that can be search in the PDF
if not possible an image of the current view

Still an ongoing ideation?
Can you please confirm the expected outcome?

> Mockup
Still items to review IMO to make it unique and not a copy from Office.
Let's discuss about it

**Comment by Julien-Dubois-eXo** [comment]
`if the field is inactive could we still provide value thanks to CSV or AS/LDAP for it?
QUID about the organizational chart?`
I had one but was not convinced by it. I'm interested in your point of view.

`Mail: to send a mail with the default mailing software of the device`
It's a feature asked by @margondicco. It opens the mail software of the device with the user email address.

 `chip to indicate the number of N-1 user linked to this users - no action on this chip`
Yes why not. I just want to say there is no action on click. I have not think about the tooltip yet. I will do it during the US redaction. 

`if possible a PDF with all the text that can be search in the PDF
if not possible an image of the current view`
It's more depending on the technical feasibility. The ideal expected outcome is the PDF. @ahamdi is currently checking that point. 

No problem discussing the mock-ups there are some points I have difficulty to do it with Miro.

**Comment by srenault-meeds** [comment]
> Mail: to send a mail with the default mailing software of the device
It's a feature asked by @margondicco. It opens the mail software of the device with the user email address.

Is that really mandatory? Indeed, we might have cases where we have hide emails. Example: Builders -> Email are hidden
Option suggested: If you really want to display the email in the card, then use the option to list other items in the card (instead of the city, the department, etc.)

**Comment by srenault-meeds** [comment]
Excepted this point, GO Func for me.
Tell me if objection regarding email

**Comment by margondicco** [comment]
No objection with your proposal @srenault-meeds . Indeed some of our client don't want email.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have changed the designed of the organisational chart settings based on your proposition. 
@margondicco FYI

**Comment by srenault-meeds** [comment]
Go Func

**Comment by boubaker** [comment]
Go tech

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds ready to be tested on MIPs-acceptance.

**Comment by ahamdi** [comment]
PR to merge proposed 

- https://github.com/Meeds-io/social/pull/3762
- https://github.com/Meeds-io/notes/pull/969
- https://github.com/Meeds-io/gatein-portal/pull/883
- https://github.com/Meeds-io/meeds/pull/1936

**Comment by srenault-meeds** [comment]
Hello

LGTM except one thing. Why am I authorized to update the setting of a chart even when not an admin?
<img width="963" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/ce363cec-dcbf-4703-ba40-dc5bb40d08b1">

**Comment by ahamdi** [comment]
> Hello
> 
> LGTM except one thing. Why am I authorized to update the setting of a chart even when not an admin? <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/58853195/328161082-ce363cec-dcbf-4703-ba40-dc5bb40d08b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTkwODYsIm5iZiI6MTcxNDk5ODc4NiwicGF0aCI6Ii81ODg1MzE5NS8zMjgxNjEwODItY2UzNjNjZWMtZGNiZi00NzAzLWJhNDAtZGM1YmI0MGQwOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzY2FiMzRiZDE2MGQ2M2ViYTU1NzUyMGJmYmY0MzhmMGQzM2FlZTNkMjg0OGQ5OTMxMDE5MjMxNmQzZWMwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BCwSCAeB1LeHAhrWExd3Ku2_2CZh6uNKWvHs9uvS5eI">

@srenault-meeds I agree the configuration button should not be visible for normal users. we will fix it asap cc @Julien-Dubois-eXo

**Comment by srenault-meeds** [comment]
Hi @ahamdi @margondicco 

We discussed about a flag for meeds package to not display the org. chart to users as it is not relevant.
Can you please provide us the property to change so I can test it out?

Thanks.

cc @plamarque

**Comment by srenault-meeds** [comment]
As discussed with @margondicco, the organizational chart access will be hidden from the time the manager field is not enabled from profile administration

**Comment by srenault-meeds** [comment]
Hello @Julien-Dubois-eXo @rdenarie it seems this is still pending.
We (meedslab) suggest to push it to develop.
And we hope that you will be able to hide the org chart if needed, but afterwards

cc @margondicco

**Comment by ahamdi** [comment]
> Hello @Julien-Dubois-eXo @rdenarie it seems this is still pending. We (meedslab) suggest to push it to develop. And we hope that you will be able to hide the org chart if needed, but afterwards
> 
> cc @margondicco

Hi @srenault-meeds , everything is OK from our side, I updated the feature/mips and the pull requests for develop. many feedback were already fixed and integrated in the merge PR including the hiding of the My Team and Organizationalchart pages when manager field is disabled
But I had some DB issues with acceptance server that I want to investigate and understand its causes. It should be ok for tomorrow, I will ping you once it is done

**Comment by srenault-meeds** [comment]
Ok tell me once available to test it out

**Comment by srenault-meeds** [comment]
Hello,
Ok for me.
The organizational chart is hidden once the Profile Field "Manager" is hidden

FYI, we still have this feedback ;-)  No blocker of course! So, let's merge it to develop if ok technically speaking (PR incl.)

> Why am I authorized to update the setting of a chart even when not an admin?

cc @Julien-Dubois-eXo @margondicco @ahamdi @rdenarie @boubaker

**Comment by boubaker** [comment]
> Hello, Ok for me. The organizational chart is hidden once the Profile Field "Manager" is hidden
> 
> FYI, we still have this feedback ;-) No blocker of course! So, let's merge it to develop if ok technically speaking (PR incl.)
> 
> > Why am I authorized to update the setting of a chart even when not an admin?
> 
> cc @Julien-Dubois-eXo @margondicco @ahamdi @rdenarie @boubaker

cool :+1: No objection for me
